### ISSUE TITLE
Benutzer anmeldung

### ISSUE THREAD

**Issue by Janis0001** [echterWagraini/4AHINF-ShellyPlugS-EPIK#1]
Der Benutzer sollte in der Lage sein sich mit einem vorhandenem Konto anzumelden oder falls noch kein Konto erstellt wurde sich einen Benutzer mit seiner E-Mail zu erstellen, ebenfalls sollte es eine Möglichkeit der Passwort Wiederherstellung geben

Priorität: 1

Akzeptanzkriterium: Anforderungen der Beschreibung erfüllt

Tasks:
- [x] Anmeldung in HTML/CSS erstellen @Janis0001 
- [x] Backend der Anmeldung @echterWagraini 
- [x] Passwort Wiederherstellung implementieren

**Comment by echterWagraini** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/4AHINF-ShellyPlugS-EPIK-63be7c17e1c22e0011276149/issues/echterWagraini/4AHINF-ShellyPlugS-EPIK/1?planning-poker) with Zenhub @Janis0001 @Vitten69
