### ISSUE TITLE
Benutzer Daten speichern

### ISSUE THREAD

**Issue by Janis0001** [echterWagraini/4AHINF-ShellyPlugS-EPIK#2]
Die Daten eines Benutzer sollten in einer Datenbank gesichert werden,
der Nutzer sollte auch seine Werte und seinen maximalen Stromverbrauch selbst konfigurieren können. Folgende Informationen sollen also über Benutzer gespeichert werden: Benutzername, Email, Passwort, Limit maximaler Stromverbrauch.

Priorität: 1

Akzeptanzkriterium: Wenn man einen Benutzer anlegt, sollen die Daten von ihm gespeichert werden.

Tasks:
- [x] Datenbank einrichten @Amsnir 
- [x] Anmeldung mit Datenbank verknüpfen @Amsnir

**Comment by echterWagraini** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/4AHINF-ShellyPlugS-EPIK-63be7c17e1c22e0011276149/issues/echterWagraini/4AHINF-ShellyPlugS-EPIK/2?planning-poker) with Zenhub @Janis0001 @Vitten69
